M48
; DRILL file {KiCad 7.0.9} date Wed Jan 17 13:02:19 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-17T13:02:19-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.2756Y-3.4646
X5.2756Y-5.0197
X6.2992Y-3.4646
X6.2992Y-5.0197
T0
M30
